# Generated by Django 3.1.4 on 2021-01-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_customuser_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rut',
            field=models.IntegerField(default=0),
        ),
    ]
