# Generated by Django 3.1.4 on 2021-01-31 16:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='default.jpg', upload_to='imagenes_perfil')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 16, 38, 32, 992482, tzinfo=utc), verbose_name='Última conexión'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 16, 38, 32, 992482, tzinfo=utc), verbose_name='Última conexión'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rut',
            field=models.IntegerField(unique=True, verbose_name='Rut'),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
