# Generated by Django 3.1.5 on 2021-02-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20210131_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinero',
            name='dinero',
            field=models.IntegerField(default=500),
        ),
    ]
