# Generated by Django 3.1.5 on 2021-02-03 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20210203_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='moverdinero',
            name='fecha_de_movimiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
