# Generated by Django 3.1.5 on 2021-02-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_moverdinero_fecha_de_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moverdinero',
            name='fecha_de_movimiento',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
