# Generated by Django 3.1.5 on 2021-02-03 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20210203_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moverdinero',
            name='fecha_de_movimiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
