# Generated by Django 3.1.5 on 2021-01-22 23:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20210122_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fecha_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 23, 9, 37, 630805, tzinfo=utc)),
        ),
    ]
