# Generated by Django 3.1.4 on 2021-01-26 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
