# Generated by Django 3.1.4 on 2021-02-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfildelusuario_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfildelusuario',
            name='about_me',
            field=models.CharField(default='Este soy yo', max_length=40),
        ),
        migrations.AlterField(
            model_name='perfildelusuario',
            name='image',
            field=models.ImageField(default='default_profile.jpg', upload_to='profile_images', verbose_name='Imagen'),
        ),
    ]
