# Generated by Django 3.1.4 on 2021-01-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210126_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rut',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
