# Generated by Django 3.1.4 on 2021-02-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20210228_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfildelusuario',
            name='about_me',
            field=models.CharField(blank=True, default='Cuentanos sobre ti', max_length=40, verbose_name='Sobre mí'),
        ),
    ]
