# Generated by Django 3.1.4 on 2021-02-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20210228_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfildelusuario',
            name='about_me',
            field=models.CharField(blank=True, max_length=40, verbose_name='Sobre mí'),
        ),
    ]
