# Generated by Django 3.1.4 on 2021-03-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20210228_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfildelusuario',
            name='image',
            field=models.ImageField(default='C:\\Users\\tekke\\Desktop\\programs\\curso-python\\archivos_django\\app_blog2\\app_blog2/usuarios/static/images/default_profile.jpg', upload_to='profile_images', verbose_name='Imagen'),
        ),
    ]
