# Generated by Django 3.1.4 on 2021-03-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20210305_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfildelusuario',
            name='image',
            field=models.ImageField(default='default_profile.jpg', upload_to='profile_images', verbose_name='Imagen'),
        ),
    ]
