# Generated by Django 3.1.5 on 2021-01-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20210130_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.customuser'),
        ),
    ]
