# Generated by Django 3.1.4 on 2021-02-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210213_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['created_at'], 'verbose_name': 'Articulo', 'verbose_name_plural': 'Articulos'},
        ),
    ]
