# Generated by Django 3.1.4 on 2021-02-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210215_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='desctiption',
        ),
    ]
