# Generated by Django 3.1.4 on 2021-02-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_category_desctiption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='imageArticles/', verbose_name='Imagen'),
        ),
    ]
