# Generated by Django 3.1.4 on 2021-03-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.CharField(max_length=100, verbose_name='Comentario'),
        ),
    ]
