# Generated by Django 3.1.5 on 2021-01-22 22:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20210122_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fecha_publicado',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 22, 22, 51, 5, 738137, tzinfo=utc)),
        ),
    ]
